apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      initContainers:
      - name: check-dispatch
        image: busybox:1.28 # or another suitable image containing netcat or curl
        command:
          - 'sh'
          - '-c'
          - 'until nc -z dispatch 8080; do echo waiting for dispatch; sleep 2; done' # Replace with the correct hostname and port if different
      
      containers:
      - name: payment
        image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
          {{- end }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      {{- with .Values.payment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.payment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.payment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secret }}
      {{- if .Values.secret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
      {{- end }}
      {{- end }}